swagger: '2.0'
info:
  title: hello world
  x-ibm-name: hello-world
  version: 1.0.0
schemes:
  - https
basePath: /hello-world
security:
  - clientIdHeader: []
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: (($httpVerb() = 'GET' and $operationPath() = '/hello'))
              execute: []
            - condition: 'true'
              execute: []
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |-
            var apim = require('apim');
            var _json = {};
            var _name = apim.getvariable('request.parameters.name');
            _json.message = "Hi " + _name;
            apim.setvariable('message.body', _json);
            apim.setvariable('message.status.code', 200);
  properties:
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  my-response:
    type: object
    additionalProperties: false
    properties:
      message:
        type: string
    x-ibm-schema:
      type: xsd
      file: >-
        PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48eHM6c2NoZW1hIHhtbG5zOnhzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIgYXR0cmlidXRlRm9ybURlZmF1bHQ9InVucXVhbGlmaWVkIiBlbGVtZW50Rm9ybURlZmF1bHQ9InF1YWxpZmllZCI+PHhzOmVsZW1lbnQgbmFtZT0ibWVzc2FnZSIgdHlwZT0ieHM6c3RyaW5nIj48L3hzOmVsZW1lbnQ+PC94czpzY2hlbWE+
paths:
  /hello:
    get:
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/my-response'
      parameters:
        - name: name
          in: query
          required: false
          type: string
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    options:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
host: $(catalog.host)
